exclude:
  - node_modules
  - frontend/node_modules
  - backend/node_modules
  - **/node_modules/**
  - frontend/**/node_modules/**
  - backend/**/node_modules/**
  # Optionally exclude app folders if you don’t publish the app via Pages
  - frontend/
  - backend/